---
all:
  hosts:
    node0:
      ansible_host: 10.14.40.140
    reg:
      ansible_host: 10.14.40.185
    # node2:
    #   ansible_host: 10.14.40.142
  children:
    clust:
      hosts:
        node0:
