---
- name: Setup slab reg
  hosts: reg
  become: true
  roles:
    - registry

- name: Setup slab clust
  hosts: clust
  become: true
  vars:
    manage_docker_service: true
    docker_daemon_options:
      insecure-registries:
        - "registry.slab.lan"
        - "registry.slab.lan:5000"
  roles:
    - ecshreve.docker
    - hashi
    - consul
    - nomad
  tasks:
    - name: Add user 'eric' to docker group
      ansible.builtin.user:
        name: eric
        groups: docker
        append: true
