---
- name: Setup slab reg
  hosts: reg
  become: true
  roles:
    - registry

- name: Setup slab clust
  hosts: 
    - worker0
    - worker1
  become: true
  vars:
    nfs_src: "10.14.40.107:/volume1/slab-clust"
    nfs_dst: "/mnt/slab-clust"
    manage_docker_service: true
    docker_daemon_options:
      insecure-registries:
        - "registry.slab.lan"
        - "registry.slab.lan:5000"
  roles:
    - general
    - ecshreve.docker
    - hashi
    - consul
    - nomad
  tasks:
    - name: Add user 'eric' to docker group
      ansible.builtin.user:
        name: eric
        groups: docker
        append: true
