---
- name: Setup devbox
  hosts: devbox
  become: true
  tasks:
    - name: Install packages for docker install
      ansible.builtin.package:
        name:
          - ca-certificates
          - curl
          - gnupg
          - python3
          - python3-pip
        state: present
        update-cache: true

    - name: Ensure old versions of Docker are NOT installed
      ansible.builtin.package:
        name:
          - docker
          - docker-engine
          - docker
          - docker.io
          - containerd
          - runc
        state: absent
        update-cache: true

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: true
      notify: Restart docker
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        executable: pip3
        name: docker
      notify: Restart docker
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Add user 'eric' to docker group
      ansible.builtin.user:
        name: eric
        groups: docker
        append: true

  handlers:
    - name: Restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true
      ignore_errors: "{{ ansible_check_mode }}"
