---
- name: Setup docker
  hosts: all
  become: true
  roles:
    - docker
  tasks:
    - name: Add user 'eric' to docker group
      ansible.builtin.user:
        name: eric
        groups: docker
        append: true

