---
- name: Pull, tag, and push docker images to local registry
  hosts: reg
  tasks:
    - name: Handle new images local docker registry
      ansible.builtin.include_role:
        name: registry-image
      vars:
        reg_addr: "registry.slab.lan:5000"
        repo_name: "{{ item.key }}"
        base_repo: "{{ item.value.repo }}"
        base_tag: "{{ item.value.tag }}"
      loop: "{{ images | dict2items }}"
  ignore_errors: "{{ ansible_check_mode }}"
  vars:
    images:
      adminer:
        repo: adminer
        tag: 4.8.1
      mariadb:
        repo: mariadb
        tag: 10.5.8
      redis:
        repo: redis
        tag: 7
      prometheus:
        repo: prom/prometheus
        tag: v2.47.0
      grafana:
        repo: grafana/grafana
        tag: 10.1.2
      loki:
        repo: grafana/loki
        tag: 2.9.1
