---
- name: Pull, tag, and push docker images to local registry
  hosts: reg
  tasks:
    - name: Handle new images local docker registry
      ansible.builtin.include_role:
        name: registry-image
      vars:
        reg_addr: "registry.slab.lan:5000"
        repo_name: "{{ item.key }}"
        base_repo: "{{ item.value.repo }}"
        base_tag: "{{ item.value.tag }}"
      loop: "{{ images | dict2items }}"
  ignore_errors: "{{ ansible_check_mode }}"
  vars:
    images:
      statty:
        repo: ecshreve/statty
        tag: 0.0.1
      # csi-nfs-plugin:
      #   repo: registry.gitlab.com/rocketduck/csi-plugin-nfs
      #   tag: 0.7.0
      # storage-controller:
      #   repo: registry.gitlab.com/rocketduck/csi-plugin-nfs
      #   tag: 0.7.0
      # storage-node:
      #   repo: registry.gitlab.com/rocketduck/csi-plugin-nfs
      #   tag: 0.7.0
      # organizr:
      #   repo: organizr/organizr
      #   tag: latest
      # calibre:
      #   repo: linuxserver/calibre-web
      #   tag: 0.6.20
      # uptime:
      #   repo: louislam/uptime-kuma
      #   tag: 1.23.2-debian
      # adminer:
      #   repo: adminer
      #   tag: 4.8.1
      # mariadb:
      #   repo: linuxserver/mariadb
      #   tag: 10.11.5
      # redis:
      #   repo: redis
      #   tag: 7
      # prometheus:
      #   repo: prom/prometheus
      #   tag: v2.47.0
      # grafana:
      #   repo: grafana/grafana
      #   tag: 10.1.2
      # loki:
      #   repo: grafana/loki
      #   tag: 2.9.1
      # promtail:
      #   repo: grafana/promtail
      #   tag: 2.9.1
      # node-exporter:
      #   repo: prom/node-exporter
      #   tag: v1.6.1
      # whoami:
      #   repo: traefik/whoami
      #   tag: v1.10.1
      # speedtest:
      #   repo: linuxserver/librespeed
      #   tag: 5.2.5
